// Этот файл содержит API ключи и должен игнорироваться в git
window.OPENAI_API_KEY = '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';
